version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install postgresql && npm i --save-dev
      - run: sudo service postgresql restart
      - run: NODE_PATH=. node sago up --app=./tests --full --down | tee | sudo -u postgres psql
      - run: NODE_PATH=. ./node_modules/c8/bin/c8.js node ./tests

